version: "3.9"

services:
  db:
    image: mysql:8.0.30
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=eternal
      - MYSQL_DATABASE=eternal
      - MYSQL_USER=eternal
      - MYSQL_PASSWORD=eternal123
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql
      - db_config:/etc/mysql/mysql.conf.d
  oauth2:
    image: quay.io/keycloak/keycloak:22.0.5
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=eternal
      - KEYCLOAK_ADMIN_PASSWORD=eternal123
    ports:
      - '8081:8080'
  amqp:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=eternal
      - RABBITMQ_DEFAULT_PASS=eternal123
    ports:
      - 5672:5672
      - 15672:15672
    labels:
      org.springframework.boot.ignore: true


volumes:
  db_data:
  db_config:
  db_logs:
