springdoc:
  default-produces-media-type: application/json

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eternal
    username: eternal
    password: eternal123
  jpa:
    show-sql: true
  mvc:
    problemdetails:
      enabled: true
  servlet.multipart:
    max-file-size: 4MB
    max-request-size: 4MB
