app.holidays:
  persistence-type: file
  persistence-file: holidays.json
  pre-seed: true
springdoc:
  default-produces-media-type: application/json

spring.servlet.multipart:
  max-file-size: 4MB
  max-request-size: 4MB
