springdoc:
  default-produces-media-type: application/json

spring:
  datasource:
    url: jdbc:h2:./dev-db
    driver-class-name: org.h2.Driver
  mvc:
    problemdetails:
      enabled: true
  servlet.multipart:
    max-file-size: 4MB
    max-request-size: 4MB
