app:
  customer:
    show-gdpr: true
logging:
  group:
    com.softarc.eternal: warn
app.holiday:
  persistence-type: file
  persistence-file: holidays.json
  pre-seed: true

spring:
  mvc:
    problemdetails:
      enabled: true
